name: Build & Deploy Develop
run-name: Building and Deploying Bonfire website on Develop  🚀
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm ci --prefix source/frontend \
          npm --prefix source/frontend run postinstall

      - name: Build Next.js application
        run: | 
          touch ./source/frontend/.env
          echo DATOCMS_READONLY_API_TOKEN=${{ secrets.DATOCMS_READONLY_API_TOKEN }} >> ./source/frontend/.env
          echo LEVER_TOKEN=${{ secrets.LEVER_TOKEN }} >> ./source/frontend/.env
          echo RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED=${{ vars.RECOIL_DUPLICATE_ATOM_KEY_CHECKING_ENABLED }} >> ./source/frontend/.env
          echo LEVER_ENDPOINT=${{ vars.LEVER_ENDPOINT }} >> ./source/frontend/.env
          echo BUCKET_NAME=${{ vars.BUCKET_NAME }} >> ./source/frontend/.env                                        
          npm install --prefix source/frontend

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./source/frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Auth with Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./source/frontend/out/

      - name: Upload to Google Cloud Storage
        run: |
          gcloud storage rm -R 'gs://${{ vars.BUCKET_NAME }}/**'
          gcloud storage cp -R './source/frontend/out/**' 'gs://${{ vars.BUCKET_NAME }}/'
