name: Build & Deploy Develop
run-name: Building and Deploying Bonfire website on Develop  🚀
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install --prefix source/frontend

      - name: Build Next.js application
        run: npm --prefix source/frontend run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./source/frontend/out/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Auth with Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./source/frontend/out/

      - name: Upload to Google Cloud Storage
        run: |
          echo ${{ vars.BUCKET_NAME }}
          echo 'gs://${{ vars.BUCKET_NAME }}/**'
          echo "gs://${{ vars.BUCKET_NAME }}/**"
          gcloud storage rm -R 'gs://${{ vars.BUCKET_NAME }}/**'
          gcloud storage cp -R './source/frontend/out/' 'gs://${{ vars.BUCKET_NAME }}/'